# Q7-How to get the common items between two python numpy arrays?

In [6]:
# Finding common values between 1d arrays
import numpy as np
    
# create 2 arrays
a = np.array([2, 4, 7, 1, 4])
b = np.array([7, 2, 9, 0, 5])
  
# Display the arrays
print("Original arrays", a, ' ', b)
  
# use the np.intersect1d method
c = np.intersect1d(a, b)
  
# Display result
print("Common values", c)

Original arrays [2 4 7 1 4]   [7 2 9 0 5]
Common values [2 7]


In [5]:
# Finding common values between n-dimensional arrays
a = np.array([2,4,7,1,4,9]).reshape(3,2)
b = np.array([7,2,9,0,5,3]).reshape(2,3)
  
# Display the arrays
print("Original arrays")
print(a)
print(b)
  
# use the np.intersect1d method
c = np.intersect1d(a,b)
  
# Display result
print("Common values",c)

Original arrays
[[2 4]
 [7 1]
 [4 9]]
[[7 2 9]
 [0 5 3]]
Common values [2 7 9]
